// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tpcp
NumericVector tpcp(NumericVector T, NumericVector p);
RcppExport SEXP _wsif97_tpcp(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tpcp(T, p));
    return rcpp_result_gen;
END_RCPP
}
// tpcv
NumericVector tpcv(NumericVector T, NumericVector p);
RcppExport SEXP _wsif97_tpcv(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tpcv(T, p));
    return rcpp_result_gen;
END_RCPP
}
// tpe
NumericVector tpe(NumericVector T, NumericVector p);
RcppExport SEXP _wsif97_tpe(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tpe(T, p));
    return rcpp_result_gen;
END_RCPP
}
// tph
NumericVector tph(NumericVector T, NumericVector p);
RcppExport SEXP _wsif97_tph(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tph(T, p));
    return rcpp_result_gen;
END_RCPP
}
// tpi
NumericVector tpi(NumericVector T, NumericVector p);
RcppExport SEXP _wsif97_tpi(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tpi(T, p));
    return rcpp_result_gen;
END_RCPP
}
// tpr
NumericVector tpr(NumericVector T, NumericVector p);
RcppExport SEXP _wsif97_tpr(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tpr(T, p));
    return rcpp_result_gen;
END_RCPP
}
// tps
NumericVector tps(NumericVector T, NumericVector p);
RcppExport SEXP _wsif97_tps(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tps(T, p));
    return rcpp_result_gen;
END_RCPP
}
// tpu
NumericVector tpu(const NumericVector T, const NumericVector p);
RcppExport SEXP _wsif97_tpu(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tpu(T, p));
    return rcpp_result_gen;
END_RCPP
}
// tpv
NumericVector tpv(NumericVector T, NumericVector p);
RcppExport SEXP _wsif97_tpv(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tpv(T, p));
    return rcpp_result_gen;
END_RCPP
}
// tpw
NumericVector tpw(NumericVector T, NumericVector p);
RcppExport SEXP _wsif97_tpw(SEXP TSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(tpw(T, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wsif97_tpcp", (DL_FUNC) &_wsif97_tpcp, 2},
    {"_wsif97_tpcv", (DL_FUNC) &_wsif97_tpcv, 2},
    {"_wsif97_tpe", (DL_FUNC) &_wsif97_tpe, 2},
    {"_wsif97_tph", (DL_FUNC) &_wsif97_tph, 2},
    {"_wsif97_tpi", (DL_FUNC) &_wsif97_tpi, 2},
    {"_wsif97_tpr", (DL_FUNC) &_wsif97_tpr, 2},
    {"_wsif97_tps", (DL_FUNC) &_wsif97_tps, 2},
    {"_wsif97_tpu", (DL_FUNC) &_wsif97_tpu, 2},
    {"_wsif97_tpv", (DL_FUNC) &_wsif97_tpv, 2},
    {"_wsif97_tpw", (DL_FUNC) &_wsif97_tpw, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_wsif97(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
