# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Specific isobaric heat capacity vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   Specific isobaric heat capacity, [\eqn{kJ/kg/K}]
#' @export
tpcp <- function(T, p) {
    .Call('_wsif97_tpcp', PACKAGE = 'wsif97', T, p)
}

#' Specific isochoric heat capacity vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   Specific isochoric heat capacity, [\eqn{kJ/kg/K}]
#' @export
tpcv <- function(T, p) {
    .Call('_wsif97_tpcv', PACKAGE = 'wsif97', T, p)
}

#' Cubic expansion coefficient vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   cubic expansion coefficient, [\eqn{1/K}]
#' @export
tpe <- function(T, p) {
    .Call('_wsif97_tpe', PACKAGE = 'wsif97', T, p)
}

#' Specific enthalpy vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   specific enthalpy, [\eqn{kJ/kg/K}]
#' @export
tph <- function(T, p) {
    .Call('_wsif97_tph', PACKAGE = 'wsif97', T, p)
}

#' Isothermal compressibility vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   Isothermal compressibility, [\eqn{1/MPa}]
#' @export
tpi <- function(T, p) {
    .Call('_wsif97_tpi', PACKAGE = 'wsif97', T, p)
}

#' Specific entropy vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   specific entropy, [\eqn{kJ/kg/K}]
#' @export
tps <- function(T, p) {
    .Call('_wsif97_tps', PACKAGE = 'wsif97', T, p)
}

#' Specific internal energy vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   specific internal energy, [\eqn{kJ/kg}]
#' @export
tpu <- function(T, p) {
    .Call('_wsif97_tpu', PACKAGE = 'wsif97', T, p)
}

#' @title Specific volume vs temperature and pressure
#'
#' @description
#'   Calculate \emph{specific volume} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   In current version numerical consistency of the specific volume
#'   in \emph{Region 3} of \emph{IAPWS R7-97} is considered sufficient enough
#'   for most applications. That is why no additional iteration procedures are
#'   used for reaching higher accuracy in this region.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   specific volume, [\eqn{m^3/kg}], or error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30)  # [MPa]
#'  tpv(t, p)
#'
#' @export
tpv <- function(T, p) {
    .Call('_wsif97_tpv', PACKAGE = 'wsif97', T, p)
}

#' Speed of sound vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   Speed of sound, [\eqn{m/s}]
#' @export
tpw <- function(T, p) {
    .Call('_wsif97_tpw', PACKAGE = 'wsif97', T, p)
}

