# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Isobaric heat capacity vs temperature and pressure
#'
#' @description
#'   Calculate specific \emph{isobaric heat capacity} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   The accuracy of calculation for this property in \emph{Region 3} depends
#'   on accuracy of \emph{specific volume} in this region. See details for
#'   \code{\link{tpv}}.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   specific isobaric heat capacity, [\eqn{kJ/kg/K}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tpcp(t, p)
#'
#' @export
tpcp <- function(T, p) {
    .Call('_wsif97_tpcp', PACKAGE = 'wsif97', T, p)
}

#' @title Isochoric heat capacity vs temperature and pressure
#'
#' @description
#'   Calculate specific \emph{isochoric heat capacity} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   The accuracy of calculation for this property in \emph{Region 3} depends
#'   on accuracy of \emph{specific volume} in this region. See details for
#'   \code{\link{tpv}}.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   specific isochoric heat capacity, [\eqn{kJ/kg/K}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tpcv(t, p)
#'
#' @export
tpcv <- function(T, p) {
    .Call('_wsif97_tpcv', PACKAGE = 'wsif97', T, p)
}

#' @title Expansion coefficient vs temperature and pressure
#'
#' @description
#'   Calculate \emph{cubic expansion coefficient} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   The accuracy of calculation for this property in \emph{Region 3} depends
#'   on accuracy of \emph{specific volume} in this region. See details for
#'   \code{\link{tpv}}.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   cubic expansion coefficient, [\eqn{1/K}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'
#'   \item \href{http://www.iapws.org/relguide/Advise5.pdf}{IAPWS AN5-13(2016)},
#'   Advisory Note No. 5: \emph{Industrial Calculation of the Thermodynamic
#'   Properties of Seawater}. September 2013.//'
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tpe(t, p)
#'
#' @export
tpe <- function(T, p) {
    .Call('_wsif97_tpe', PACKAGE = 'wsif97', T, p)
}

#' @title Enthalpy vs temperature and pressure
#'
#' @description
#'   Calculate specific \emph{enthalpy} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   The accuracy of calculation for this property in \emph{Region 3} depends
#'   on accuracy of \emph{specific volume} in this region. See details for
#'   \code{\link{tpv}}.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   specific enthalpy, [\eqn{kJ/kg}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tph(t, p)
#'
#' @export
tph <- function(T, p) {
    .Call('_wsif97_tph', PACKAGE = 'wsif97', T, p)
}

#' @title Compressibility vs temperature and pressure
#'
#' @description
#'   Calculate \emph{isothermal compressibility} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   The accuracy of calculation for this property in \emph{Region 3} depends
#'   on accuracy of \emph{specific volume} in this region. See details for
#'   \code{\link{tpv}}.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   isothermal compressibility, [\eqn{1/MPa}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'
#'   \item \href{http://www.iapws.org/relguide/Advise5.pdf}{IAPWS AN5-13(2016)},
#'   Advisory Note No. 5: \emph{Industrial Calculation of the Thermodynamic
#'   Properties of Seawater}. September 2013.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tpi(t, p)
#'
#' @export
tpi <- function(T, p) {
    .Call('_wsif97_tpi', PACKAGE = 'wsif97', T, p)
}

#' @title Mass density vs temperature and pressure
#'
#' @description
#'   Calculate \emph{mass density} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   The accuracy of calculation for this property in \emph{Region 3} depends
#'   on accuracy of \emph{specific volume} in this region. See details for
#'   \code{\link{tpv}}.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   mass density, [\eqn{kg/m^3}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tpr(t, p)
#'
#' @export
tpr <- function(T, p) {
    .Call('_wsif97_tpr', PACKAGE = 'wsif97', T, p)
}

#' @title Entropy vs temperature and pressure
#'
#' @description
#'   Calculate specific \emph{entropy} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   The accuracy of calculation for this property in \emph{Region 3} depends
#'   on accuracy of \emph{specific volume} in this region. See details for
#'   \code{\link{tpv}}.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   specific entropy, [\eqn{kJ/kg/K}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tps(t, p)
#'
#' @export
tps <- function(T, p) {
    .Call('_wsif97_tps', PACKAGE = 'wsif97', T, p)
}

#' @title Internal energy vs temperature and pressure
#'
#' @description
#'   Calculate specific \emph{internal energy} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   The accuracy of calculation for this property in \emph{Region 3} depends
#'   on accuracy of \emph{specific volume} in this region. See details for
#'   \code{\link{tpv}}.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   specific internal energy, [\eqn{kg/m^3}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tpu(t, p)
#'
#' @export
tpu <- function(T, p) {
    .Call('_wsif97_tpu', PACKAGE = 'wsif97', T, p)
}

#' @title Specific volume vs temperature and pressure
#'
#' @description
#'   Calculate \emph{specific volume} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   In current version numerical consistency of the specific volume
#'   in \emph{Region 3} of \emph{IAPWS R7-97} is considered sufficient enough
#'   for most applications. That is why no additional iteration procedures are
#'   used for reaching higher accuracy in this region.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   specific volume, [\eqn{m^3/kg}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tpv(t, p)
#'
#' @export
tpv <- function(T, p) {
    .Call('_wsif97_tpv', PACKAGE = 'wsif97', T, p)
}

#' @title Speed of sound vs temperature and pressure
#'
#' @description
#'   Calculate \emph{speed of sound} as a function of \emph{temperature} and
#'   \emph{pressure} in accordance with \emph{IAPWS R7-97} formulation.
#'
#' @family properties in temperature-pressure space
#'
#' @details
#'   Vectors \code{T} and \code{p} both must have the same length. Default
#'   \href{https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Vector-arithmetic}{recycling rules}
#'   are not applicable in this context.
#'
#'   The accuracy of calculation for this property in \emph{Region 3} depends
#'   on accuracy of \emph{specific volume} in this region. See details for
#'   \code{\link{tpv}}.
#'
#' @param T
#'   absolute temperature in validity range 273.15 -- 2273.15, [\emph{K}].
#'   Type: \code{NumericVector}
#' @param p
#'   absolute pressure in validity range 0 -- 100 \emph{MPa}, [\emph{MPa}].
#'   Type: \code{NumericVector}
#' @return
#'   speed of sound, [\eqn{m/s}], or the next error code:
#'   \describe{
#'       \item{\code{-10}}{
#'         Fail to determine region in temperature-pressure space into which the
#'         entire range of validity of \emph{IAPWS R7-97}
#'         is divided. Possibly values of one or both arguments are
#'         out of bounds or in undeterminable subspace.
#'       }
#'       \item{\code{-20}}{
#'         Fail to determine subregion inside \emph{Region 3} in accordance
#'         with \emph{IAPWS SR5-05}. Possibly values of one or both arguments
#'         are in undeterminable subspace or near singularity.
#'       }
#'   }
#'   Type: \code{NumericVector}
#'
#' @references
#'  \itemize{
#'   \item \href{http://www.iapws.org/relguide/IF97-Rev.pdf}{IAPWS R7-97 (2012)},
#'   \emph{Revised Release on the IAPWS Industrial Formulation 1997 for the
#'   Thermodynamic Properties of Water and Steam}. August 2007.
#'
#'   \item \href{http://www.iapws.org/relguide/Supp-VPT3-2016.pdf}{IAPWS SR5-05 (2016)},
#'   \emph{Revised Supplementary Release on Backward Equations for Specific
#'   Volume as a Function of Pressure and Temperature v(p,T) for Region 3 of the
#'   IAPWS Industrial Formulation 1997 for the Thermodynamic Properties of Water and
#'   Steam}. June 2014.
#'  }
#'
#' @examples
#'  t <- c(300,300,500,300,700,700,1500,1500,2000,0)  # [K]
#'  p <- c(3,80,3,.35e-2,.35e-2,30,.5,30,30,0)  # [MPa]
#'  tpw(t, p)
#'
#' @export
tpw <- function(T, p) {
    .Call('_wsif97_tpw', PACKAGE = 'wsif97', T, p)
}

