# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Specific isobaric heat capacity vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   Specific isobaric heat capacity, [\eqn{kJ/kg/K}]
#' @export
tpcp <- function(T, p) {
    .Call('_wsif97_tpcp', PACKAGE = 'wsif97', T, p)
}

#' Specific isochoric heat capacity vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   Specific isochoric heat capacity, [\eqn{kJ/kg/K}]
#' @export
tpcv <- function(T, p) {
    .Call('_wsif97_tpcv', PACKAGE = 'wsif97', T, p)
}

#' Cubic expansion coefficient vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   cubic expansion coefficient, [\eqn{1/K}]
#' @export
tpe <- function(T, p) {
    .Call('_wsif97_tpe', PACKAGE = 'wsif97', T, p)
}

#' Specific enthalpy vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   specific enthalpy, [\eqn{kJ/kg/K}]
#' @export
tph <- function(T, p) {
    .Call('_wsif97_tph', PACKAGE = 'wsif97', T, p)
}

#' Isothermal compressibility vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   Isothermal compressibility, [\eqn{1/MPa}]
#' @export
tpi <- function(T, p) {
    .Call('_wsif97_tpi', PACKAGE = 'wsif97', T, p)
}

#' Specific entropy vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   specific entropy, [\eqn{kJ/kg/K}]
#' @export
tps <- function(T, p) {
    .Call('_wsif97_tps', PACKAGE = 'wsif97', T, p)
}

#' Specific internal energy vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   specific internal energy, [\eqn{kJ/kg}]
#' @export
tpu <- function(T, p) {
    .Call('_wsif97_tpu', PACKAGE = 'wsif97', T, p)
}

#' Specific volume vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   specific volume, [\eqn{m^3/kg}]
#' @export
tpv <- function(T, p) {
    .Call('_wsif97_tpv', PACKAGE = 'wsif97', T, p)
}

f <- function(T, r) {
    .Call('_wsif97_f', PACKAGE = 'wsif97', T, r)
}

#' Speed of sound vs temperature and pressure
#'
#' @param T
#'   absolute temperature, [\emph{K}]
#' @param p
#'   absolute pressure, [\emph{MPa}]
#' @return
#'   Speed of sound, [\eqn{m/s}]
#' @export
tpw <- function(T, p) {
    .Call('_wsif97_tpw', PACKAGE = 'wsif97', T, p)
}

